services:
  mongodb:
    image: mongo:latest
    container_name: url-shortener-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: urlshortener
    volumes:
      - mongo-data:/data/db
    networks:
      - url-shortener-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/urlshortener
    depends_on:
      - mongodb
    networks:
      - url-shortener-net

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend/url-shortener-ui
      dockerfile: ../Dockerfile
    container_name: url-shortener-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - url-shortener-net

volumes:
  mongo-data:

networks:
  url-shortener-net: